name: Manually triggered DD event
on: 
  workflow_dispatch:
    inputs:
      event_text:
        description: 'Event Text'
jobs:
  send-event:
    name: Send Event to Datadog
    runs-on: ubuntu-latest
    steps:
      - name: Datadog
        uses: kennonkwok/datadog-actions@63ddec6150df06f2e111a99565ff5d4ea08b0631
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          events: |
            - title: "Hello Datadog!"
              text: "${{ github.event.inputs.event_text }}"
              alert_type: "info"
              source_type_name: "GITHUB"
              host: "github/${{ github.repository_owner }}"
              tags:
                - "project:${{ github.repository }}"
                - "triggered_by:${{ github.actor }}"